### ISSUE TITLE
Use `Option` and `Result` combinators for more streamlined code

### ISSUE THREAD

**Issue by coriolinus** [solidiquis/ez_encrypt#1]
https://github.com/solidiquis/ez_encrypt/blob/034246f49b2118f88639746f96ad7c90dbb25a02/server/src/main.rs#L30-L34

You could simplify this pattern:

```rust
let host = dotenv::var("HOST").unwrap_or_else("0.0.0.0".to_string());
```

You could avoid the `to_string` allocation by converting to `Ipv4Addr` inline:

```rust
let host = dotenv::var("HOST")
    .map(|host_str| host_str.parse::<std::net::Ipv4Addr>())
    .transpose()?
    .unwrap_or(Ipv4Addr::new(0, 0, 0, 0))
```

You could also use these patterns later for `port`.

**Comment by solidiquis** [comment]
38a2bdd79984a8642d41919757eca1d4fd0fa989
