### ISSUE TITLE
Use the `?` operator for more streamlined code.

### ISSUE THREAD

**Issue by coriolinus** [solidiquis/ez_encrypt#2]
https://github.com/solidiquis/ez_encrypt/blob/034246f49b2118f88639746f96ad7c90dbb25a02/client/src/crypto/mod.rs#L13

This can be written as

```rust
validate_key(keyb)?;
```

This has the same effect but is shorter and simpler to read (for someone experienced in Rust).

**Comment by solidiquis** [comment]
38a2bdd79984a8642d41919757eca1d4fd0fa989
