### ISSUE TITLE
Replace manual padding loop with `resize`

### ISSUE THREAD

**Issue by coriolinus** [solidiquis/ez_encrypt#3]
https://github.com/solidiquis/ez_encrypt/blob/034246f49b2118f88639746f96ad7c90dbb25a02/client/src/crypto/util.rs#L6-L10

This can be rewritten as 

```rust
plain_textb.resize(plain_textb.len() + num_padding, 32);
```

**Comment by solidiquis** [comment]
38a2bdd79984a8642d41919757eca1d4fd0fa989
