### ISSUE TITLE
Use `u32::to_be_bytes` to transform `u32` into `[u8; 4]`

### ISSUE THREAD

**Issue by coriolinus** [solidiquis/ez_encrypt#4]
https://github.com/solidiquis/ez_encrypt/blob/034246f49b2118f88639746f96ad7c90dbb25a02/client/src/crypto/util.rs#L15-L22

You're manually reimplementing [`u32::to_be_bytes`](https://doc.rust-lang.org/stable/std/primitive.u32.html#method.to_be_bytes).

**Comment by solidiquis** [comment]
38a2bdd79984a8642d41919757eca1d4fd0fa989
