### ISSUE TITLE
Convert directly to arrays instead of allocating an intermediate vector

### ISSUE THREAD

**Issue by coriolinus** [solidiquis/ez_encrypt#5]
https://github.com/solidiquis/ez_encrypt/blob/034246f49b2118f88639746f96ad7c90dbb25a02/client/src/crypto/mod.rs#L22-L28

You can convert a slice directly into an array with `try_into`; see [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cd278fa9e91eb9f92c2bb3f8d348cedb).

That gives you

```rust
let lblock: [u8; 4] = block[0..4].try_into().expect("selected four bytes");
let rblock: [u8; 4] = block[4..8].try_into().expect("selected four bytes");

 let [lenc_block, renc_block] = bf.bc_encrypt([ 
     u32::from_be_bytes(lblock), 
     u32::from_be_bytes(rblock) 
 ]); 
```

**Comment by solidiquis** [comment]
38a2bdd79984a8642d41919757eca1d4fd0fa989
